"""
Django settings for NewStart project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=o^6a(*msphyhbzm*vyg-bb%7g%g4fq2h-7tlu5!4#8l^z5*8r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'newstartapp',
    'tailwind',
    'theme',
    'CodeLogic',
    'background_task',
     'django_celery_results'
    
]
TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
ROOT_URLCONF = 'NewStart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NewStart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'newstart',
        'USER': 'Arko',
        'PASSWORD': 'Thelastships1_',
        'HOST': 'scrapingdb.clqe0qkwapvo.eu-north-1.rds.amazonaws.com',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
NPM_BIN_PATH= r"C:\Program Files\nodejs\npm.cmd" 


#celery settings
CELERY_BROKER_URL=os.environ.get('CELERY_BROKER_URL') #Tells Celery to use Redis running locally (127.0.0.1:6379) as the message broker for task queues.Initially it goes for celery_broker_url tho
CELERY_ACCEPT_CONTENT=['application/json'] # Celery will only accept tasks serialized in JSON format
CELERY_RESULT_SERIALIZER='json' #Tasks and results will be encoded/decoded as JSON
CELERY_TASK_SERIALIZER='json'
CELERY_TIMEZONE='Asia/Kolkata' # Sets the timezone to India (Kolkata) for task schedules                                       JSON = JavaScript Object Notation – A lightweight format for storing/transferring data (like a Python dict but for all languages).Looks like this: {"name": "Alice", "age": 25, "pets": ["dog", "cat"]} (Keys + values in quotes).
CELERY_RESULT_BACKEND=os.environ.get('CELERY_RESULT_BACKEND')

#download button stuff
MEDIA_URL = '/media/'    ##MEDIA_URL defines the URL path used to access those files in the browser. When someone visits a link starting with /media/, Django knows to fetch the file from MEDIA_ROOT.
MEDIA_ROOT = BASE_DIR / 'media' ##MEDIA_ROOT defines the physical location on the server where files (like CSVs, images, PDFs) are stored. Here, it means Django will save files inside a folder named media in your project’s base directory.

##ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,16.170.170.187").split(",") ##getting it to read from the environment(nano .env file)
ALLOWED_HOSTS = ["*"]
    ##'ENGINE': 'django.db.backends.postgresql',
      ##  'NAME': 'newstart',
        ##'USER': 'Arko',
        ##'PASSWORD': 'Thelastships1_',
        ##'HOST': 'scrapingdb.clqe0qkwapvo.eu-north-1.rds.amazonaws.com',
        ##'PORT': '432',

          ##  'ENGINE': 'django.db.backends.sqlite3',
        ##'NAME': BASE_DIR / "db.sqlite3",