# Generated by Django 5.2.3 on 2025-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GBPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('PhoneNumber', models.CharField(max_length=500)),
                ('MapLink', models.CharField(max_length=500)),
                ('Website', models.CharField(blank=True, max_length=500)),
                ('Email', models.CharField(blank=True, max_length=500)),
                ('Linkedin', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
