# Generated by Django 5.2.3 on 2025-07-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GBPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=500)),
                ('Address', models.CharField(blank=True, max_length=500)),
                ('PhoneNumber', models.CharField(blank=True, max_length=500)),
                ('MapLink', models.CharField(blank=True, max_length=500)),
                ('Website', models.CharField(blank=True, max_length=500)),
                ('Email', models.CharField(blank=True, max_length=500)),
                ('Linkedin', models.CharField(blank=True, max_length=500)),
                ('Stat', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=500)),
                ('Address', models.CharField(blank=True, max_length=500)),
                ('PhoneNumber', models.CharField(blank=True, max_length=500)),
                ('MapLink', models.CharField(blank=True, max_length=500)),
                ('Website', models.CharField(blank=True, max_length=500)),
                ('Email', models.CharField(blank=True, max_length=500)),
                ('Linkedin', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companynumber', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Num1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procID', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QueryStartStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QueryStopStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
            ],
        ),
    ]
