# Generated by Django 5.2.3 on 2025-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companynumber', models.IntegerField()),
            ],
        ),
    ]
